name: CICD
on:
  workflow_dispatch:
   inputs:
    environment:
     description: This is the environment value  where this worklow runs 
     default: 'dev'
     required: true
     type: choice
     options:
       - dev
       - prod
       - staging
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from GitHub"
  build:
      runs-on: ubuntu-latest
      steps:
        - name: build docker container
          run: echo "docker container build"
  test:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: test the container
            run: echo "testing the container"
  deploy:
        if: inputs.environment == 'dev'  #deploy will run only when the environment is dev
        needs: [build,test]
        runs-on: ubuntu-latest
        steps:
          - name: Deploying the app
            run: echo "Docker compose deployed the app"
