name: Deploy Flask App

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted
        env:
            DOCKER_HUB_USER: ${{vars.DOCKER_HUB_USER}}
        steps:
          - name: checkout code
            uses: actions/checkout@v4

          - name: Set up docker compose (optional, usually pre-installed on ubuntu-latest)
            uses: docker/setup-compose-action@v2 

          - name: deploy with docker compose
            run: docker compose up -d 

